#!/bin/bash 

# This script makes new matlab function files with cli options

## Constants

RIGHT_NOW="$(date +"%x %r %Z")"
TIME_STAMP="Updated $RIGHT_NOW by $USER"
SCRIPT="$(basename $0)"

## Functions

write_file(){
    write_header
    write_inputs
    write_returns
    write_comments
    write_code
}

write_header(){
    cat <<- _EOF_
function [$returns] = $function($inputs)
%
% $function:
%   $desc
%
% Usage:
%   [$returns] = $function($inputs);
_EOF_
}

write_inputs(){
    OIFS=$IFS
    IFS=','
    read -ra inputlist <<< "$inputs"
    echo "%"
    echo "% Inputs:"
    for i in "${inputlist[@]}";
    do
        printf "%%%8s: \n" $i
    done
    IFS=$OIFS
}

write_returns(){
    OIFS=$IFS
    IFS=','
    read -ra returnlist <<< "$returns"
    echo "%"
    echo "% Outputs:"
    for r in "${returnlist[@]}";
    do
        printf "%%%8s: \n" $r
    done
    IFS=$OIFS
}

write_comments(){
    cat <<- _EOF_
%
% Comments:
%   $comment
%
_EOF_
}

write_code(){
    echo
    for r in "${returnlist[@]}";
    do
        printf "%s = \n" $r
    done
    echo
    echo "end"
}

usage(){
    echo "usage: $SCRIPT [option]..."
}

help(){
    usage
    echo "Create a new Matlab function from a template."
    echo
    echo "  -o,  --output              output filename         (filename.tex)"
    echo "  -d,  --directory           directory               (scripts/)"
    echo "  -i,  --inputs              function inputs         (x, y)"
    echo "  -r,  --returns             function returns        (w, z)"
    echo "  -D,  --description         header description of function"
    echo "  -c,  --comment             header comment about function"
    echo "  -h,  --help                display this help and exit"
    echo
    echo "Visit https://github.com/tdpage/matlab_tools for more info"
}

## Main

# initialize some fields
filename=       # filename including extension
function=       # function name
dir=            # directory to place file
inputs=         # comma separated list of inputs
returns=        # comma separated list of returns
desc=           # function description
comment=        # general comment under the header


# read flags
while [ "$1" != "" ]; do
    case $1 in
        -o | --output      )      shift
                                  filename=$1
                                  ;;
        -d | --directory   )      shift
                                  dir=$1
                                  ;;
        -i | --inputs      )      shift
                                  inputs=$1
                                  ;;
        -r | --returns     )      shift
                                  returns=$1
                                  ;;
        -D | --description )      shift
                                  desc=$1
                                  ;;
        -c | --comment     )      shift
                                  comment=$1
                                  ;;
        -h | --help        )      help
                                  exit
                                  ;;
        * )                       usage
                                  exit 1
    esac
    shift
done

# if certain fields haven't been entered, set some defaults based on the filename
[[ "$filename" = "" ]]    && filename="myfun.m"
[[ "$function" = "" ]]    && function=${filename%.*}
[[ "$inputs"   = "" ]]    && inputs="x"
[[ "$returns"  = "" ]]    && returns="y"
[[ "$desc"     = "" ]]    && desc="Matlab Function to ..."
[[ "$comment"  = "" ]]    && comment=""
# [[ "$dir" = "" ]]         && dir=""

 
# if scripts directory exists, add it to dir path
if [[ -d "./scripts" ]]; then
    dir="scripts/$dir"
fi

# do some work
[[ -d "./$dir" ]] || mkdir -p ./$dir
[[ -f "./$dir$filename" ]] || write_file > ./$dir$filename
exit 0


